language: node_js

sudo: false
node_js:
  - "4"

addons:
  apt_packages:
    - pandoc

cache:
  apt: true
  directories:
    - node_modules
    - themes/next/node_modules
branches:
  only:
  - blog-source

before_install:
- openssl aes-256-cbc -K $encrypted_5e358a4badeb_key -iv $encrypted_5e358a4badeb_iv
  -in .travis/ssh_key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "szpssky"
- git config --global user.email "szpssky@gmail.com"

install:
- npm install -g hexo-cli
- npm install
- npm install hexo-renderer-pandoc --save
- npm install hexo-algolia --save
- npm install gulp -g
- npm install gulp-minify-css gulp-uglify gulp-htmlmin gulp-htmlclean gulp --save

script:
- export HEXO_ALGOLIA_INDEXING_KEY=4dc503e864a56a3318a7346d174c1242
- hexo cl
- hexo algolia
- hexo g
- gulp
- hexo d
