language: node_js

node_js:
  - "4"

branches:
  only:
  - blog-source

before_install:
- openssl aes-256-cbc -K $encrypted_5e358a4badeb_key -iv $encrypted_5e358a4badeb_iv
  -in .travis/ssh_key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "szpssky"
- git config --global user.email "szpssky@gmail.com"

install:
- npm install -g hexo-cli
- npm update -g minimatch@3.0.2
- npm install
- ls
- cd node_modules
- ls
- cd ..

script:
- hexo cl
- hexo g
